import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import AuthLayout from '../components/AuthLayout'
import { useAuth } from '../context/AuthContext'

export default function Signup() {
	const { signup } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ displayName: '', username: '', password: '', confirmPassword: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const update = (key) => (event) => setForm({ ...form, [key]: event.target.value })
	async function submit(event) { event.preventDefault(); setError(''); setBusy(true); try { await signup(form); navigate('/') } catch (cause) { setError(cause.message) } finally { setBusy(false) } }
	return <AuthLayout eyebrow="Start your circle" title={<>Make room for<br /><em>more connection.</em></>} description="A private place for the people and moments that matter most."><form className="auth-form signup-form" onSubmit={submit}><div className="profile-upload"><div className="upload-avatar">＋</div><div><strong>Add a profile photo</strong><span>Optional · You can do this later</span></div><button type="button">Upload</button></div><label>Display name<input value={form.displayName} onChange={update('displayName')} placeholder="How should we call you?" autoComplete="name" required /></label><label>Username<div className="input-prefix"><span>@</span><input value={form.username} onChange={update('username')} placeholder="Choose a username" autoComplete="username" required /></div><small>3–20 characters · letters, numbers, underscores</small></label><div className="form-grid"><label>Password<input value={form.password} onChange={update('password')} type="password" placeholder="Create a password" autoComplete="new-password" required /></label><label>Confirm password<input value={form.confirmPassword} onChange={update('confirmPassword')} type="password" placeholder="Repeat password" autoComplete="new-password" required /></label></div>{error && <p className="form-error">{error}</p>}<button className="primary-button" type="submit" disabled={busy}>{busy ? 'Creating account...' : 'Create account'} <span>→</span></button></form><p className="auth-switch">Already have an account? <Link to="/login">Log in</Link></p></AuthLayout>
}